### ISSUE TITLE
Key family upgrades

### ISSUE THREAD

**Issue by maxtaco** [keybase/node-client#192]
Upgrade the node client so it understands modern key families.  This will basically be a port of `keyfamily.go` in the Go client.

Plan:
   - [x] In `Sigchain.verify_sig`, run the whole chain through the new libkeybase-js library; pre-fill a list of all of those signatures previously checked; update all chainlinks with a "checked" bit before writing them back to DB.
   - [x] Check the `@key` variable against the keys returned from `Sigchain.replay`.
   - [x] Add ChainLink types for sibkeys and subkeys, so no warnings when inserting them into the IdTable. They otherwise can be ignored.
   - [x]  Find someway to get the single, blessed PGP key for new accounts, so the old code can work mainly unmodified.
   - [x] Fail gracefully as possible for those users with no viable PGP keys
   - [x] Update tracking statements to track eldest KIDs

**Comment by maxtaco** [comment]
Plan:
  1. In `Sigchain.verify_sig`, run the whole chain through the new libkeybase-js library; pre-fill a list of all of those signatures previously checked; update all chainlinks with a "checked" bit before writing them back to DB.
  1. Check the `@key` variable against the keys returned from `Sigchain.replay`.

**Comment by oconnor663** [comment]
The first two commits for this are 71728c32393cfa181e4a5683cbf58cbc35177792 (just dependency updates) and f98d2b5959cfa4321d50e5833a8f9055e501b74c (calling the new Merkle tree implementation).

**Comment by oconnor663** [comment]
Next commit (larger refactor of sigchain.iced and user.iced) 4c6f027f66568020fb87edd37a3e50f77176c743

**Comment by oconnor663** [comment]
Just landed like seven commits on master, including updates to keybase-proofs and kbpgp.
