### ISSUE TITLE
Spotty missing from bundleDependencies?

### ISSUE THREAD

**Issue by tdb** [keybase/node-client#193]
Should ```spotty``` be included in the ```bundleDependencies``` section of ```package.json```? Perhaps it was missed in 996897a727fba4da08d564bad1d13d074bdb663c.

I'm trying to use the client on FreeBSD, and I get the error:

```
Error: Cannot find module 'spotty'
```

And indeed spotty is not included inside the tar file. It'd be great if this could be fixed for 0.7.8?

**Comment by maxtaco** [comment]
great point, i'll fix!

**Comment by maxtaco** [comment]
Checked in a fix, it will go live with the next release.  Thanks!
