### ISSUE TITLE
Cache new-style chain signature verifications

### ISSUE THREAD

**Issue by maxtaco** [keybase/node-client#198]
First, this depends on keybase/libkeybase-js#2 working properly.  Next, we need a way to write out all verified sig-ids, and read them back from the local DB, so we can remember across executions which signatures are verified.

**Comment by oconnor663** [comment]
Done, but needs an integration test.

**Comment by oconnor663** [comment]
81e30a615b5ae807d64f65577319b3af43f8abd5
