### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by asgrim** [keybase/node-client#222]
I get the message:

```
The Keybase Node.js client is no longer supported.
Please upgrade to our new and improved client via:

    https://keybase.io/download

Thank you!
```

when I run keybase CLI, which is fine.

But how do I uninstall this version (and `keybase-installer`) first please?

**Comment by maxtaco** [comment]
```
npm uninstall -g keybase-installer
npm uninstall -g keybase
```

**Comment by asgrim** [comment]
Thanks! Works perfectly. Perhaps some instruction in that deprecation message would be helpful for others who aren't familiar with npm :) thanks!

**Comment by maxtaco** [comment]
Good idea, that was an oversight on our part!
